#!/usr/bin/env python3
"""
Generate authentic human-voice audio for every phrase in index.html using
Google Cloud Text-to-Speech (Neural2, Latin-American Spanish).

It reads the Spanish phrases straight out of index.html so the audio can never
drift from what the app shows, calls Google TTS for each, saves audio/NNN.mp3,
and writes audio-map.js (the lookup the app uses to play the right clip).

Setup:
  1. Get a Google Cloud API key with the "Cloud Text-to-Speech API" enabled.
  2. Put it in cancun-phrases/.env  ->  GOOGLE_TTS_API_KEY=AIza...
     (optional)                        GOOGLE_TTS_VOICE=es-US-Neural2-B
     (optional)                        GOOGLE_TTS_RATE=0.95
  3. Run:  python generate_audio.py

No third-party packages required.
"""
import os, re, sys, json, base64, urllib.request, urllib.error

HERE = os.path.dirname(os.path.abspath(__file__))
HTML = os.path.join(HERE, "index.html")
AUDIO_DIR = os.path.join(HERE, "audio")
MAP_JS = os.path.join(HERE, "audio-map.js")
ENV = os.path.join(HERE, ".env")

API = "https://texttospeech.googleapis.com/v1/text:synthesize?key={key}"


def load_env():
    """Minimal .env loader (KEY=VALUE per line)."""
    if os.path.exists(ENV):
        with open(ENV, encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if not line or line.startswith("#") or "=" not in line:
                    continue
                k, v = line.split("=", 1)
                os.environ.setdefault(k.strip(), v.strip().strip('"').strip("'"))


def extract_phrases():
    """Pull field[0] (Spanish) of each ["es","en","phon"] row in index.html, in order, de-duped."""
    with open(HTML, encoding="utf-8") as f:
        html = f.read()
    rows = re.findall(r'\[\s*"((?:[^"\\]|\\.)*)"\s*,\s*"', html)
    seen, ordered = set(), []
    for es in rows:
        es = es.encode().decode("unicode_escape") if "\\" in es else es
        if es not in seen:
            seen.add(es)
            ordered.append(es)
    return ordered


def synth(text, key, voice, rate):
    lang = "-".join(voice.split("-")[:2])  # es-US-Neural2-B -> es-US
    body = json.dumps({
        "input": {"text": text},
        "voice": {"languageCode": lang, "name": voice},
        "audioConfig": {"audioEncoding": "MP3", "speakingRate": float(rate)},
    }).encode("utf-8")
    req = urllib.request.Request(
        API.format(key=key), data=body,
        headers={"Content-Type": "application/json"},
    )
    with urllib.request.urlopen(req, timeout=30) as r:
        payload = json.loads(r.read().decode("utf-8"))
    return base64.b64decode(payload["audioContent"])


def main():
    load_env()
    key = os.environ.get("GOOGLE_TTS_API_KEY")
    if not key:
        sys.exit("ERROR: set GOOGLE_TTS_API_KEY in cancun-phrases/.env (see header).")
    voice = os.environ.get("GOOGLE_TTS_VOICE", "es-US-Neural2-B")
    rate = os.environ.get("GOOGLE_TTS_RATE", "0.95")

    phrases = extract_phrases()
    total_chars = sum(len(p) for p in phrases)
    print(f"{len(phrases)} phrases, {total_chars} characters, voice={voice}, rate={rate}")

    os.makedirs(AUDIO_DIR, exist_ok=True)
    audio_map = {}
    for i, es in enumerate(phrases, 1):
        fname = f"{i:03d}.mp3"
        path = os.path.join(AUDIO_DIR, fname)
        rel = f"audio/{fname}"
        audio_map[es] = rel
        if os.path.exists(path) and os.path.getsize(path) > 0:
            print(f"  [{i:>3}] skip (exists)  {es}")
            continue
        try:
            mp3 = synth(es, key, voice, rate)
        except urllib.error.HTTPError as e:
            detail = e.read().decode("utf-8", "ignore")
            sys.exit(f"\nGoogle TTS error {e.code} on '{es}':\n{detail}")
        with open(path, "wb") as f:
            f.write(mp3)
        print(f"  [{i:>3}] saved {len(mp3):>6}B  {es}")

    with open(MAP_JS, "w", encoding="utf-8") as f:
        f.write("// Auto-generated by generate_audio.py — maps each phrase to its recording.\n")
        f.write("window.AUDIO_MAP = ")
        json.dump(audio_map, f, ensure_ascii=False, indent=1)
        f.write(";\n")

    print(f"\nDone. {len(audio_map)} clips in audio/, lookup written to audio-map.js")


if __name__ == "__main__":
    main()
